name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "$" > "$HOME/.ssh/HOSTKEY"
      - run: chmod 600 "$HOME/.ssh/HOSTKEY"
      - run: rsync -e "ssh -p 22 -i $HOME/.ssh/HOSTKEY -o StrictHostKeyChecking=no" --archive --compress --delete . u1675238.cp.regruhosting.ru:/var/www/u1675238/public_html/ilyabrekhov.ru
